<!DOCTYPE html>
<html>
<head>
	<title>Promosi Barang dan Jasa</title>
	<style>
		body {
			font-family: Arial, sans-serif;
		}
		
		.promosi {
			width: 75%;
			margin: 30px auto;
			background-color: #f2f2f2;
			padding: 20px;
			border: 1px solid #ddd;
			box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
		}
		
		.promosi img {
			width: 70%;
			height: 2
			100px;
			object-fit: cover;
			border-radius: 400px 400px 0 0;
		}
		
		.promosi h2 {
			font-size: 32px;
			margin-top: 20px;
		}
		
		.promosi p {
			font-size: 24px;
			color: #666;
		}
		
		.promosi button {
			background-color: #4CAF50;
			color: #fff;
			padding: 10px 20px;
			border: none;
			border-radius: 5px;
			cursor: pointer;
		}
		
		.promosi button:hover {
			background-color: #3e8e41;
		}
	</style>
</head>
<div class="promosi">
    <img src="logo.jpeg">
</head>
<body>
	<div class="promosi">
		<img src="pulsa.jpeg" alt="Gambar Promosi">
		<h2>4TUNE</h2>
		<p>PULSA DAN PAKET DATA MURAH!</p>
		<p>Harga: Rp 10.000 - Rp 50.000</p>
        <p>HUB 0895356441406</p>
		<button>BELI SEKARANG</button>
	</div>
    
</style>
</head>
<body>
<div class="promosi">
    <img src="tisu masker.jpeg" alt="Gambar Promosi">
    <h2>4TUNE</h2>
    <p>TISSU DAN MASKER GROSIR MURAH!</p>
    <p>Harga: Rp 7.500/Pcs dan Rp 50.000/Ktk</p>
    <p>PROMO RAMADHAN 2025</p>
    <button>BELI SEKARANG</button>
</div>

<body>
	<div class="promosi">
		<img src="buket.jpeg" alt="Gambar Promosi">
		<h2>4TUNE</h2>
		<p>BUKET BUNGA DAN MAKANAN!</p>
		<p>Harga: Rp 15.000</p>
		<p>BUKET PERNIHAKAN, PERPISAHAN, WISUDA, DLL</p>
		<button>BELI SEKARANG</button>
	</div>

</style>
</head>
<body>
<div class="promosi">
    <img src="banner.jpeg" alt="Gambar Promosi">
    <h2>4TUNE</h2>
    <p>DESAIN DAN CETAK BANNER!</p>
    <p>Harga: Rp 15.000/m</p>
    <p>Gratis Biaya Desain dan Antar</p>
    <button>HUBUNGI SEKARANG</button>
</div>
<body>
	<div class="kotak">
 

		<div class="blok">
 
			<h2>Informasi</h2>			

 
			<div class="kanan">
				<table>
					<tr>
						<th>Nama</th>
						<th>:</th>
						<td>Muhammad Akbar Ferdiyanto</td>
					</tr>
					<tr>
						<th>Tempat</th>
						<th>:</th>
						<td>Palembang</td>
					</tr>
					
					<tr>
						<th>Alamat</th>
						<th>:</th>
						<td>Lr. Sersan II, Kota Palembang</td>
					</tr>
					<tr>
						<th>Email</th>
						<th>:</th>
						<td>4tune@gmail.cm</td>
					</tr>
					<tr>
						<th>No.HP</th>
						<th>:</th>
						<td>+62812-3456-7890</td>
					</tr>
				</table>
				
			</div>
</body>
</html>
